# Generated by Django 4.2 on 2023-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crednow', '0002_chatbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
